apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-manager-cluster
  namespace: scylla-manager
spec:
  version: 4.5.1
  agentVersion: 2.5.2
  repository: docker.io/scylladb/scylla
  agentRepository: docker.io/scylladb/scylla-manager-agent
  developerMode: true
  cpuset: false
  datacenter:
    name: manager-dc
    racks:
      - name: manager-rack
        members: 1
        storage:
          capacity: 5Gi
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 100Mi
