# Version information
scyllaImage:
  tag: 4.5.1
agentImage:
  tag: 2.5.2

# Cluster information
developerMode: true
datacenter: us-east-1
racks:
- name: us-east-1b
  members: 2
  storage:
    capacity: 5Gi
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi
